### PR TITLE
Add language support in NavMenu

### PR DESCRIPTION
**Pull request by mwjames**
image

image

image

### CODE REVIEW

**Comment by mwjames** [comment]
@s7eph4n Not sure that the implementation is what you want but it does what I need.

**Comment by s7eph4n** [comment]
I'm reluctant to add more special values to the sidebar.

Would it work to introduce a boolean attribute `showLanguages` for the NavMenu that will make it show the languages? E.g.

```XML
				<component type="NavbarHorizontal">
					<component type="Logo" position="head"></component>
					<component type="NavMenu" flatten="navigation" showLanguages="1" ></component>
					<component type="PageTools" position="right" hideSelectedNameSpace="1"></component>
					<component type="SearchBar" position="right"></component>
					<component type="PersonalTools" position="right"></component>
				</component>
```

Another attribute `hideLanguages` would hide them on the Toolbar.

Positioning of the language submenu among the other NavMenu entries would then be done by just placing LANGUAGES in Mediawiki:Sidebar where it is needed:
```
* About
* LANGUAGES
* Tests
```

**Comment by mwjames** [comment]
> I'm reluctant to add more special values to the sidebar.

That's fine. So yes, a boolean works as well, I just don't want to scroll down to find out that a page has other languages available.

**Comment by s7eph4n** [comment]
It's in: https://gerrit.wikimedia.org/r/#/c/273982/

**Comment by mwjames** [comment]
:+1:

**Pull request closed without merging**
